### ISSUE TITLE
FK Nodes Transparency

### ISSUE THREAD

**Issue by wampxs** [krypto5863/Illusion.StudioNodeTweaks#1]
Hello! This mod has a lot of potential, but at the moment, FK Nodes are fully opaque when the mod is installed. This makes it very inconvenient to work with, specially when the LookAt node is turned on (which also becomes opaque).

Would it be possible to implement the same changes you did to IK nodes for FK too? Letting the user change individual colors, alphas and specially tweak the LookAt node individually would be pretty great.

**Comment by krypto5863** [comment]
You can already change FK color nodes in the game, and the transparency can be modified in the plugin settings, why not check that out?
